# Generated by Django 5.2.13 on 2026-04-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('sunrise', 'Sunrise'), ('sunset', 'Sunset'), ('other', 'Other')], max_length=20),
        ),
    ]
