# Generated by Django 5.2.13 on 2026-04-23 02:54

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0004_alter_moment_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='visibility_mode',
            field=models.CharField(choices=[('private', 'Private'), ('tagged', 'Tagged People'), ('custom', 'Custom'), ('friends', 'Friends')], default='tagged', max_length=20),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('requester', models.F('addressee')), _negated=True), name='friendship_requester_not_addressee'), models.UniqueConstraint(django.db.models.functions.comparison.Least('requester', 'addressee'), django.db.models.functions.comparison.Greatest('requester', 'addressee'), name='friendship_unique_unordered_pair')],
            },
        ),
    ]
