# Generated by Django 5.2.13 on 2026-05-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0008_pushdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='moments/thumbnails/'),
        ),
    ]
